sudo: false

language: node_js
node_js:
- "lts/*"

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

services:
  - xvfb

branches:
  only:
    - master

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get -y install libxtst-dev;
  fi
- if [ $TRAVIS_OS_NAME == "osx" ]; then
      nvm install 12.12;
  fi
- npm install -g vsce

install:
  - npm install
  - npm run vscode:prepublish
  - vsce package

script:
  - npm run tslint
  - npm run test-all --silent
