language: node_js

node_js:
- 'node'

branches:
  only:
    - master
    - jdtls-extension-ls

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
  fi

install:
  - npm install

script:
  - npm run tslint
  - npm run test
